/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualTourRouteImport } from './routes/virtual-tour'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as CollectiveRouteImport } from './routes/collective'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'

const VirtualTourRoute = VirtualTourRouteImport.update({
  id: '/virtual-tour',
  path: '/virtual-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectiveRoute = CollectiveRouteImport.update({
  id: '/collective',
  path: '/collective',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/collective': typeof CollectiveRoute
  '/destinations': typeof DestinationsRoute
  '/ecosystem': typeof EcosystemRoute
  '/investors': typeof InvestorsRoute
  '/shop': typeof ShopRoute
  '/vendors': typeof VendorsRoute
  '/virtual-tour': typeof VirtualTourRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/collective': typeof CollectiveRoute
  '/destinations': typeof DestinationsRoute
  '/ecosystem': typeof EcosystemRoute
  '/investors': typeof InvestorsRoute
  '/shop': typeof ShopRoute
  '/vendors': typeof VendorsRoute
  '/virtual-tour': typeof VirtualTourRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/collective': typeof CollectiveRoute
  '/destinations': typeof DestinationsRoute
  '/ecosystem': typeof EcosystemRoute
  '/investors': typeof InvestorsRoute
  '/shop': typeof ShopRoute
  '/vendors': typeof VendorsRoute
  '/virtual-tour': typeof VirtualTourRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/collective'
    | '/destinations'
    | '/ecosystem'
    | '/investors'
    | '/shop'
    | '/vendors'
    | '/virtual-tour'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/collective'
    | '/destinations'
    | '/ecosystem'
    | '/investors'
    | '/shop'
    | '/vendors'
    | '/virtual-tour'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/collective'
    | '/destinations'
    | '/ecosystem'
    | '/investors'
    | '/shop'
    | '/vendors'
    | '/virtual-tour'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  CollectiveRoute: typeof CollectiveRoute
  DestinationsRoute: typeof DestinationsRoute
  EcosystemRoute: typeof EcosystemRoute
  InvestorsRoute: typeof InvestorsRoute
  ShopRoute: typeof ShopRoute
  VendorsRoute: typeof VendorsRoute
  VirtualTourRoute: typeof VirtualTourRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtual-tour': {
      id: '/virtual-tour'
      path: '/virtual-tour'
      fullPath: '/virtual-tour'
      preLoaderRoute: typeof VirtualTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collective': {
      id: '/collective'
      path: '/collective'
      fullPath: '/collective'
      preLoaderRoute: typeof CollectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  CollectiveRoute: CollectiveRoute,
  DestinationsRoute: DestinationsRoute,
  EcosystemRoute: EcosystemRoute,
  InvestorsRoute: InvestorsRoute,
  ShopRoute: ShopRoute,
  VendorsRoute: VendorsRoute,
  VirtualTourRoute: VirtualTourRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
